import ROOT
from ROOT import TCanvas, TFile, TProfile, TNtuple, TH1I, TH1F, TH2F, TH3F, TColor, TEfficiency
from ROOT import gROOT, gBenchmark, gRandom, gSystem
import numpy as np
import pdb

tag = 'p011'
cent = '0-5'
hijingfile = 'dETdeta_analysis_23727_particle_reweighting_nozs_mc_reweight_0-5_hijing.root'
#hijingfile = 'dETdeta_analysis_23727_'+tag+'_nozs_mc_reweight_'+cent+'_hijing.root'
datafile = 'dETdeta_analysis_23727_'+tag+'_zs_30ADC_data_noweight_'+cent+'.root'
eposfile = 'dETdeta_analysis_23727_'+tag+'_nozs_mc_reweight_'+cent+'_epos.root'
amptfile = 'dETdeta_analysis_23727_'+tag+'_nozs_mc_reweight_'+cent+'_ampt.root'
outfile = 'dETdeta_plots_w_hijing_reweight_'+cent+'_'+tag+'.root'

runlegend = 'Run 23727-'+tag+' '+cent+'% cent.'

gROOT.LoadMacro("/sphenix/u/egm2153/spring_2023/sPhenixStyle.C");
gROOT.ProcessLine("SetsPhenixStyle()")

f1 = ROOT.TFile.Open(hijingfile)
h_eT_truth = TH1F(f1.Get("hetdeta_ihcalbin"))
h_eT_truth_ihcalbin = TH1F(f1.Get("hetdeta_ihcalbin"))
h_eT_truth_ohcalbin = TH1F(f1.Get("hetdeta_ohcalbin"))
h_eT_sim_emcal = TH1F(f1.Get("h_eT_emcal"))
h_eT_sim_ihcal = TH1F(f1.Get("h_eT_ihcal"))
h_eT_sim_ohcal = TH1F(f1.Get("h_eT_ohcal"))
h_eT_truth.SetDirectory(0)
h_eT_truth_ihcalbin.SetDirectory(0)
h_eT_truth_ohcalbin.SetDirectory(0)
h_eT_sim_emcal.SetDirectory(0)
h_eT_sim_ihcal.SetDirectory(0)
h_eT_sim_ohcal.SetDirectory(0)
f1.Close()
f2 = ROOT.TFile.Open(datafile)
h_eT_data_emcal = TH1F(f2.Get("h_eT_emcal"))
h_eT_data_ihcal = TH1F(f2.Get("h_eT_ihcal"))
h_eT_data_ohcal = TH1F(f2.Get("h_eT_ohcal"))
h_eT_data_emcal.SetDirectory(0)
h_eT_data_ihcal.SetDirectory(0)
h_eT_data_ohcal.SetDirectory(0)
f2.Close()
f3 = ROOT.TFile.Open(eposfile)
h_eT_truth_epos = TH1F(f3.Get("hetdeta_ihcalbin"))
h_eT_truth_ihcalbin_epos = TH1F(f3.Get("hetdeta_ihcalbin"))
h_eT_truth_ohcalbin_epos = TH1F(f3.Get("hetdeta_ohcalbin"))
h_eT_epos_emcal = TH1F(f3.Get("h_eT_emcal"))
h_eT_epos_ihcal = TH1F(f3.Get("h_eT_ihcal"))
h_eT_epos_ohcal = TH1F(f3.Get("h_eT_ohcal"))
h_eT_truth_epos.SetDirectory(0)
h_eT_truth_ihcalbin_epos.SetDirectory(0)
h_eT_truth_ohcalbin_epos.SetDirectory(0)
h_eT_epos_emcal.SetDirectory(0)
h_eT_epos_ihcal.SetDirectory(0)
h_eT_epos_ohcal.SetDirectory(0)
f3.Close()
f4 = ROOT.TFile.Open(amptfile)
h_eT_truth_ampt = TH1F(f4.Get("hetdeta_ihcalbin"))
h_eT_truth_ihcalbin_ampt = TH1F(f4.Get("hetdeta_ihcalbin"))
h_eT_truth_ohcalbin_ampt = TH1F(f4.Get("hetdeta_ohcalbin"))
h_eT_ampt_emcal = TH1F(f4.Get("h_eT_emcal"))
h_eT_ampt_ihcal = TH1F(f4.Get("h_eT_ihcal"))
h_eT_ampt_ohcal = TH1F(f4.Get("h_eT_ohcal"))
h_eT_truth_ampt.SetDirectory(0)
h_eT_truth_ihcalbin_ampt.SetDirectory(0)
h_eT_truth_ohcalbin_ampt.SetDirectory(0)
h_eT_ampt_emcal.SetDirectory(0)
h_eT_ampt_ihcal.SetDirectory(0)
h_eT_ampt_ohcal.SetDirectory(0)
f4.Close()

file = ROOT.TFile(outfile, "RECREATE")

emcal_canvas = TCanvas("emcal_reco","",600,500)
emcal_leg = ROOT.TLegend(.2,.2,.6,.4)
emcal_leg.AddEntry("",runlegend,"")
emcal_leg.AddEntry(h_eT_data_emcal,"Data","lep")
emcal_leg.AddEntry(h_eT_sim_emcal,"Hijing","lep")
emcal_leg.AddEntry(h_eT_epos_emcal,"EPOS","lep")
emcal_leg.AddEntry(h_eT_ampt_emcal,"AMPT","lep")
emcal_leg.SetBorderSize(0)
h_eT_data_emcal.SetLineColor(1)
h_eT_sim_emcal.SetLineColor(2)
h_eT_ampt_emcal.SetLineColor(4)
h_eT_epos_emcal.SetLineColor(3)
h_eT_data_emcal.SetMarkerStyle(20)
h_eT_sim_emcal.SetMarkerStyle(8)
h_eT_sim_emcal.SetMarkerSize(0.7)
h_eT_sim_emcal.SetMarkerColor(2)
h_eT_ampt_emcal.SetMarkerStyle(8)
h_eT_ampt_emcal.SetMarkerSize(0.7)
h_eT_ampt_emcal.SetMarkerColor(4)
h_eT_epos_emcal.SetMarkerStyle(8)
h_eT_epos_emcal.SetMarkerSize(0.7)
h_eT_epos_emcal.SetMarkerColor(3)
h_eT_data_emcal.GetYaxis().SetRangeUser(0,600)
h_eT_data_emcal.SetStats(0)
h_eT_sim_emcal.SetStats(0)
h_eT_epos_emcal.SetStats(0)
h_eT_ampt_emcal.SetStats(0)
h_eT_data_emcal.SetYTitle("EMCal Reco dE_{T}/d#eta [GeV]")
h_eT_data_emcal.SetXTitle("#eta")
h_eT_data_emcal.Draw()
h_eT_sim_emcal.Draw('same')
h_eT_epos_emcal.Draw('same')
h_eT_ampt_emcal.Draw('same')
emcal_leg.Draw()
emcal_canvas.Draw()

ihcal_canvas = TCanvas("ihcal_reco","",600,500)
ihcal_leg = ROOT.TLegend(.2,.69,.85,.89)
ihcal_leg.AddEntry("",runlegend,"")
ihcal_leg.AddEntry(h_eT_data_ihcal,"Data","lep")
ihcal_leg.AddEntry(h_eT_sim_ihcal,"Hijing","lep")
ihcal_leg.AddEntry(h_eT_epos_ihcal,"EPOS","lep")
ihcal_leg.AddEntry(h_eT_ampt_ihcal,"AMPT","lep")
ihcal_leg.SetBorderSize(0)
h_eT_data_ihcal.SetStats(0)
h_eT_sim_ihcal.SetStats(0)
h_eT_epos_ihcal.SetStats(0)
h_eT_ampt_ihcal.SetStats(0)
h_eT_data_ihcal.SetYTitle("IHCal Reco dE_{T}/d#eta [GeV]")
h_eT_data_ihcal.SetXTitle("#eta")
h_eT_data_ihcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_sim_ihcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_epos_ihcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_ampt_ihcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_data_ihcal.GetYaxis().SetRangeUser(0,80)
h_eT_sim_ihcal.GetYaxis().SetRangeUser(0,80)
h_eT_epos_ihcal.GetYaxis().SetRangeUser(0,80)
h_eT_ampt_ihcal.GetYaxis().SetRangeUser(0,80)
h_eT_data_ihcal.SetLineColor(1)
h_eT_sim_ihcal.SetLineColor(2)
h_eT_epos_ihcal.SetLineColor(3)
h_eT_ampt_ihcal.SetLineColor(4)
h_eT_data_ihcal.SetMarkerStyle(20)
h_eT_sim_ihcal.SetMarkerStyle(8)
h_eT_sim_ihcal.SetMarkerSize(0.7)
h_eT_sim_ihcal.SetMarkerColor(2)
h_eT_ampt_ihcal.SetMarkerStyle(8)
h_eT_ampt_ihcal.SetMarkerSize(0.7)
h_eT_ampt_ihcal.SetMarkerColor(4)
h_eT_epos_ihcal.SetMarkerStyle(8)
h_eT_epos_ihcal.SetMarkerSize(0.7)
h_eT_epos_ihcal.SetMarkerColor(3)
h_eT_data_ihcal.Draw()
h_eT_sim_ihcal.Draw('same')
h_eT_epos_ihcal.Draw('same')
h_eT_ampt_ihcal.Draw('same')
ihcal_leg.Draw()
ihcal_canvas.Draw()

ohcal_canvas = TCanvas("ohcal_reco","",600,500)
ohcal_leg = ROOT.TLegend(.2,.69,.85,.89)
ohcal_leg.AddEntry("",runlegend,"")
ohcal_leg.AddEntry(h_eT_data_ohcal,"Data","lep")
ohcal_leg.AddEntry(h_eT_sim_ohcal,"Hijing","lep")
ohcal_leg.AddEntry(h_eT_epos_ohcal,"EPOS","lep")
ohcal_leg.AddEntry(h_eT_ampt_ohcal,"AMPT","lep")
ohcal_leg.SetBorderSize(0)
h_eT_data_ohcal.SetStats(0)
h_eT_sim_ohcal.SetStats(0)
h_eT_epos_ohcal.SetStats(0)
h_eT_ampt_ohcal.SetStats(0)
h_eT_data_ohcal.SetYTitle("OHCal Reco dE_{T}/d#eta [GeV]")
h_eT_data_ohcal.SetXTitle("#eta")
h_eT_data_ohcal.GetYaxis().SetRangeUser(0,270)
h_eT_sim_ohcal.GetYaxis().SetRangeUser(0,270)
h_eT_epos_ohcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_epos_ohcal.GetYaxis().SetRangeUser(0,270)
h_eT_ampt_ohcal.GetYaxis().SetRangeUser(0,270)
h_eT_data_ohcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_sim_ohcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_ampt_ohcal.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_data_ohcal.SetLineColor(1)
h_eT_sim_ohcal.SetLineColor(2)
h_eT_epos_ohcal.SetLineColor(3)
h_eT_ampt_ohcal.SetLineColor(4)
h_eT_data_ohcal.SetMarkerStyle(20)
h_eT_sim_ohcal.SetMarkerStyle(8)
h_eT_sim_ohcal.SetMarkerSize(0.7)
h_eT_sim_ohcal.SetMarkerColor(2)
h_eT_ampt_ohcal.SetMarkerStyle(8)
h_eT_ampt_ohcal.SetMarkerSize(0.7)
h_eT_ampt_ohcal.SetMarkerColor(4)
h_eT_epos_ohcal.SetMarkerStyle(8)
h_eT_epos_ohcal.SetMarkerSize(0.7)
h_eT_epos_ohcal.SetMarkerColor(3)
h_eT_data_ohcal.Draw()
h_eT_sim_ohcal.Draw('same')
h_eT_epos_ohcal.Draw('same')
h_eT_ampt_ohcal.Draw('same')
ohcal_leg.Draw()
ohcal_canvas.Draw()

emcal_ratio_hijing = TH1F(h_eT_sim_emcal.Clone("emcal_ratio_hijing"))
emcal_ratio_hijing.Divide(h_eT_truth)
emcal_detdeta_hijing = TH1F(h_eT_data_emcal.Clone("emcal_detdeta_hijing"))
emcal_detdeta_hijing.Divide(emcal_ratio_hijing)
emcal_ratio_epos = TH1F(h_eT_epos_emcal.Clone("emcal_ratio_epos"))
emcal_ratio_epos.Divide(h_eT_truth_epos)
emcal_detdeta_epos = TH1F(h_eT_data_emcal.Clone("emcal_detdeta_epos"))
emcal_detdeta_epos.Divide(emcal_ratio_epos)
emcal_ratio_ampt = TH1F(h_eT_ampt_emcal.Clone("emcal_ratio_ampt"))
emcal_ratio_ampt.Divide(h_eT_truth_ampt)
emcal_detdeta_ampt = TH1F(h_eT_data_emcal.Clone("emcal_detdeta_ampt"))
emcal_detdeta_ampt.Divide(emcal_ratio_ampt)

ihcal_ratio_hijing = TH1F(h_eT_sim_ihcal.Clone("ihcal_ratio_hijing"))
ihcal_ratio_hijing.Divide(h_eT_truth_ihcalbin)
ihcal_detdeta_hijing = TH1F(h_eT_data_ihcal.Clone("ihcal_detdeta_hijing"))
ihcal_detdeta_hijing.Divide(ihcal_ratio_hijing)
ihcal_ratio_epos = TH1F(h_eT_epos_ihcal.Clone("ihcal_ratio_epos"))
ihcal_ratio_epos.Divide(h_eT_truth_ihcalbin_epos)
ihcal_detdeta_epos = TH1F(h_eT_data_ihcal.Clone("ihcal_detdeta_epos"))
ihcal_detdeta_epos.Divide(ihcal_ratio_epos)
ihcal_ratio_ampt = TH1F(h_eT_ampt_ihcal.Clone("ihcal_ratio_ampt"))
ihcal_ratio_ampt.Divide(h_eT_truth_ihcalbin_ampt)
ihcal_detdeta_ampt = TH1F(h_eT_data_ihcal.Clone("ihcal_detdeta_ampt"))
ihcal_detdeta_ampt.Divide(ihcal_ratio_ampt)

ohcal_ratio_hijing = TH1F(h_eT_sim_ohcal.Clone("ohcal_ratio_hijing"))
ohcal_ratio_hijing.Divide(h_eT_truth_ohcalbin)
ohcal_detdeta_hijing = TH1F(h_eT_data_ohcal.Clone("ohcal_detdeta_hijing"))
ohcal_detdeta_hijing.Divide(ohcal_ratio_hijing)
ohcal_ratio_epos = TH1F(h_eT_epos_ohcal.Clone("ohcal_ratio_epos"))
ohcal_ratio_epos.Divide(h_eT_truth_ohcalbin_epos)
ohcal_detdeta_epos = TH1F(h_eT_data_ohcal.Clone("ohcal_detdeta_epos"))
ohcal_detdeta_epos.Divide(ohcal_ratio_epos)
ohcal_ratio_ampt = TH1F(h_eT_ampt_ohcal.Clone("ohcal_ratio_ampt"))
ohcal_ratio_ampt.Divide(h_eT_truth_ohcalbin_ampt)
ohcal_detdeta_ampt = TH1F(h_eT_data_ohcal.Clone("ohcal_detdeta_ampt"))
ohcal_detdeta_ampt.Divide(ohcal_ratio_ampt)

emcal_corr_canvas = TCanvas("emcal_corr","",600,500)
emcal_corr_leg = ROOT.TLegend(.16,.7,.7,.89)
emcal_corr_leg.AddEntry("",runlegend,"")
emcal_corr_leg.AddEntry(emcal_ratio_hijing,"Hijing","lep")
emcal_corr_leg.AddEntry(emcal_ratio_epos,"EPOS","lep")
emcal_corr_leg.AddEntry(emcal_ratio_ampt,"AMPT","lep")
emcal_corr_leg.SetBorderSize(0)
emcal_ratio_hijing.SetMarkerStyle(20)
emcal_ratio_hijing.SetLineColor(2)
emcal_ratio_hijing.SetMarkerColor(2)
emcal_ratio_epos.SetMarkerStyle(20)
emcal_ratio_epos.SetLineColor(3)
emcal_ratio_epos.SetMarkerColor(3)
emcal_ratio_ampt.SetMarkerStyle(20)
emcal_ratio_ampt.SetLineColor(4)
emcal_ratio_ampt.SetMarkerColor(4)
emcal_ratio_hijing.GetYaxis().SetRangeUser(0,1)
emcal_ratio_epos.GetYaxis().SetRangeUser(0,1)
emcal_ratio_ampt.GetYaxis().SetRangeUser(0,1)
emcal_ratio_hijing.GetXaxis().SetRangeUser(-1.05,1.1)
emcal_ratio_epos.GetXaxis().SetRangeUser(-1.05,1.1)
emcal_ratio_ampt.GetXaxis().SetRangeUser(-1.05,1.1)
emcal_ratio_hijing.SetStats(0)
emcal_ratio_epos.SetStats(0)
emcal_ratio_ampt.SetStats(0)
emcal_ratio_hijing.SetYTitle("EMCal Reco dE_{T}/d#eta / Truth dE_{T}/d#eta")
emcal_ratio_hijing.SetXTitle("#eta")
emcal_ratio_hijing.Draw()
emcal_ratio_epos.Draw("same")
emcal_ratio_ampt.Draw("same")
emcal_corr_leg.Draw()
emcal_corr_canvas.Draw()

ihcal_corr_canvas = TCanvas("ihcal_corr","",600,500)
ihcal_corr_leg = ROOT.TLegend(.16,.7,.7,.89)
ihcal_corr_leg.AddEntry("",runlegend,"")
ihcal_corr_leg.AddEntry(ihcal_ratio_hijing,"Hijing","lep")
ihcal_corr_leg.AddEntry(ihcal_ratio_epos,"EPOS","lep")
ihcal_corr_leg.AddEntry(ihcal_ratio_ampt,"AMPT","lep")
ihcal_corr_leg.SetBorderSize(0)
ihcal_ratio_hijing.SetMarkerStyle(20)
ihcal_ratio_hijing.SetLineColor(2)
ihcal_ratio_hijing.SetMarkerColor(2)
ihcal_ratio_epos.SetMarkerStyle(20)
ihcal_ratio_epos.SetLineColor(3)
ihcal_ratio_epos.SetMarkerColor(3)
ihcal_ratio_ampt.SetMarkerStyle(20)
ihcal_ratio_ampt.SetLineColor(4)
ihcal_ratio_ampt.SetMarkerColor(4)
ihcal_ratio_hijing.GetYaxis().SetRangeUser(0,1)
ihcal_ratio_epos.GetYaxis().SetRangeUser(0,1)
ihcal_ratio_ampt.GetYaxis().SetRangeUser(0,1)
ihcal_ratio_hijing.GetXaxis().SetRangeUser(-1.05,1.1)
ihcal_ratio_epos.GetXaxis().SetRangeUser(-1.05,1.1)
ihcal_ratio_ampt.GetXaxis().SetRangeUser(-1.05,1.1)
ihcal_ratio_hijing.SetStats(0)
ihcal_ratio_epos.SetStats(0)
ihcal_ratio_ampt.SetStats(0)
ihcal_ratio_hijing.SetYTitle("IHCal Reco dE_{T}/d#eta / Truth dE_{T}/d#eta")
ihcal_ratio_hijing.SetXTitle("#eta")
ihcal_ratio_hijing.Draw()
ihcal_ratio_epos.Draw("same")
ihcal_ratio_ampt.Draw("same")
ihcal_corr_leg.Draw()
ihcal_corr_canvas.Draw()

ohcal_corr_canvas = TCanvas("ohcal_corr","",600,500)
ohcal_corr_leg = ROOT.TLegend(.16,.7,.7,.89)
ohcal_corr_leg.AddEntry("",runlegend,"")
ohcal_corr_leg.AddEntry(ohcal_ratio_hijing,"Hijing","lep")
ohcal_corr_leg.AddEntry(ohcal_ratio_epos,"EPOS","lep")
ohcal_corr_leg.AddEntry(ohcal_ratio_ampt,"AMPT","lep")
ohcal_corr_leg.SetBorderSize(0)
ohcal_ratio_hijing.SetMarkerStyle(20)
ohcal_ratio_hijing.SetLineColor(2)
ohcal_ratio_hijing.SetMarkerColor(2)
ohcal_ratio_epos.SetMarkerStyle(20)
ohcal_ratio_epos.SetLineColor(3)
ohcal_ratio_epos.SetMarkerColor(3)
ohcal_ratio_ampt.SetMarkerStyle(20)
ohcal_ratio_ampt.SetLineColor(4)
ohcal_ratio_ampt.SetMarkerColor(4)
ohcal_ratio_hijing.GetYaxis().SetRangeUser(0,1)
ohcal_ratio_epos.GetYaxis().SetRangeUser(0,1)
ohcal_ratio_ampt.GetYaxis().SetRangeUser(0,1)
ohcal_ratio_hijing.GetXaxis().SetRangeUser(-1.05,1.1)
ohcal_ratio_epos.GetXaxis().SetRangeUser(-1.05,1.1)
ohcal_ratio_ampt.GetXaxis().SetRangeUser(-1.05,1.1)
ohcal_ratio_hijing.SetStats(0)
ohcal_ratio_epos.SetStats(0)
ohcal_ratio_ampt.SetStats(0)
ohcal_ratio_hijing.SetYTitle("OHCal Reco dE_{T}/d#eta / Truth dE_{T}/d#eta")
ohcal_ratio_hijing.SetXTitle("#eta")
ohcal_ratio_hijing.Draw()
ohcal_ratio_epos.Draw("same")
ohcal_ratio_ampt.Draw("same")
ohcal_corr_leg.Draw()
ohcal_corr_canvas.Draw()

low_bound = {'0-5': 400, '5-15':300, '15-25':200, '25-35':100, '35-45':0, '45-55':0, '55-65':0}
high_bound = {'0-5': 1300, '5-15':1000, '15-25':800, '25-35':600, '35-45':450, '45-55':300, '55-65':150}

hijing_canvas = TCanvas("hijing_full_corr","",700,700)
hijing_leg = ROOT.TLegend(.16,.7,.7,.89)
hijing_leg.AddEntry("",runlegend,"")
hijing_leg.AddEntry(h_eT_truth,"HIJING dE_{T}/d#eta","lep")
hijing_leg.AddEntry(emcal_detdeta_hijing,"EMCal dE_{T}/d#eta","lep")
hijing_leg.AddEntry(ihcal_detdeta_hijing,"IHCal dE_{T}/d#eta","lep")
hijing_leg.AddEntry(ohcal_detdeta_hijing,"OHCal dE_{T}/d#eta","lep")
hijing_canvas.SetLeftMargin(0.15)
hijing_leg.SetBorderSize(0)
h_eT_truth.GetYaxis().SetRangeUser(low_bound[cent],high_bound[cent])
h_eT_truth.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_truth.SetStats(0)
h_eT_truth.SetYTitle("dE_{T}/d#eta [GeV]")
h_eT_truth.SetXTitle("#eta")
h_eT_truth.SetMarkerSize(0.7)
h_eT_truth.SetLineColor(4)
h_eT_truth.SetMarkerColor(4)
h_eT_truth.Draw()
emcal_detdeta_hijing.SetMarkerStyle(20)
emcal_detdeta_hijing.SetLineColor(2)
emcal_detdeta_hijing.SetMarkerColor(2)
emcal_detdeta_hijing.Draw("same")
ihcal_detdeta_hijing.SetMarkerStyle(20)
ihcal_detdeta_hijing.SetLineColor(3)
ihcal_detdeta_hijing.SetMarkerColor(3)
ihcal_detdeta_hijing.Draw("same")
ohcal_detdeta_hijing.SetMarkerStyle(20)
ohcal_detdeta_hijing.SetLineColor(6)
ohcal_detdeta_hijing.SetMarkerColor(6)
ohcal_detdeta_hijing.Draw("same")
#starline = ROOT.TLine(-1,620,1,620);
#phnxline = ROOT.TLine(-0.35,597,0.35,597);
#starbox = ROOT.TBox(-1,620-33,1,620+33);
#phnxbox = ROOT.TBox(-0.35,597-35,0.35,597+35);
#starline.SetLineColor(3)
#starbox.SetFillColorAlpha(3,0.3)
#phnxline.SetLineColor(4)
#phnxbox.SetFillColorAlpha(4,0.3)
#starline.Draw('same')
#starbox.Draw('same')
#phnxline.Draw('same')
#phnxbox.Draw('same')
hijing_leg.Draw()
hijing_canvas.Draw()

epos_canvas = TCanvas("epos_full_corr","",700,700)
epos_leg = ROOT.TLegend(.16,.7,.7,.89)
epos_leg.AddEntry("",runlegend,"")
epos_leg.AddEntry(h_eT_truth_epos,"EPOS dE_{T}/d#eta","lep")
epos_leg.AddEntry(emcal_detdeta_epos,"EMCal dE_{T}/d#eta","lep")
epos_leg.AddEntry(ihcal_detdeta_epos,"IHCal dE_{T}/d#eta","lep")
epos_leg.AddEntry(ohcal_detdeta_epos,"OHCal dE_{T}/d#eta","lep")
epos_canvas.SetLeftMargin(0.15)
epos_leg.SetBorderSize(0)
h_eT_truth_epos.GetYaxis().SetRangeUser(low_bound[cent],high_bound[cent])
h_eT_truth_epos.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_truth_epos.SetStats(0)
h_eT_truth_epos.SetYTitle("dE_{T}/d#eta [GeV]")
h_eT_truth_epos.SetXTitle("#eta")
h_eT_truth_epos.SetMarkerSize(0.7)
h_eT_truth_epos.SetLineColor(4)
h_eT_truth_epos.SetMarkerColor(4)
h_eT_truth_epos.Draw()
emcal_detdeta_epos.SetMarkerStyle(20)
emcal_detdeta_epos.SetLineColor(2)
emcal_detdeta_epos.SetMarkerColor(2)
emcal_detdeta_epos.Draw("same")
ihcal_detdeta_epos.SetMarkerStyle(20)
ihcal_detdeta_epos.SetLineColor(3)
ihcal_detdeta_epos.SetMarkerColor(3)
ihcal_detdeta_epos.Draw("same")
ohcal_detdeta_epos.SetMarkerStyle(20)
ohcal_detdeta_epos.SetLineColor(6)
ohcal_detdeta_epos.SetMarkerColor(6)
ohcal_detdeta_epos.Draw("same")
#starline = ROOT.TLine(-1,620,1,620)
#phnxline = ROOT.TLine(-0.35,597,0.35,597)
#starbox = ROOT.TBox(-1,620-33,1,620+33)
#phnxbox = ROOT.TBox(-0.35,597-35,0.35,597+35)
#starline.SetLineColor(3)
#starbox.SetFillColorAlpha(3,0.3)
#phnxline.SetLineColor(4)
#phnxbox.SetFillColorAlpha(4,0.3)
#starline.Draw('same')
#starbox.Draw('same')
#phnxline.Draw('same')
#phnxbox.Draw('same')
epos_leg.Draw()
epos_canvas.Draw()

ampt_canvas = TCanvas("ampt_full_corr","",700,700)
ampt_leg = ROOT.TLegend(.16,.7,.7,.89)
ampt_leg.AddEntry("",runlegend,"")
ampt_leg.AddEntry(h_eT_truth_ampt,"AMPT dE_{T}/d#eta","lep")
ampt_leg.AddEntry(emcal_detdeta_ampt,"EMCal dE_{T}/d#eta","lep")
ampt_leg.AddEntry(ihcal_detdeta_ampt,"IHCal dE_{T}/d#eta","lep")
ampt_leg.AddEntry(ohcal_detdeta_ampt,"OHCal dE_{T}/d#eta","lep")
ampt_canvas.SetLeftMargin(0.15)
ampt_leg.SetBorderSize(0)
h_eT_truth_ampt.GetYaxis().SetRangeUser(low_bound[cent],high_bound[cent])
h_eT_truth_ampt.GetXaxis().SetRangeUser(-1.05,1.1)
h_eT_truth_ampt.SetStats(0)
h_eT_truth_ampt.SetYTitle("dE_{T}/d#eta [GeV]")
h_eT_truth_ampt.SetXTitle("#eta")
h_eT_truth_ampt.SetMarkerSize(0.7)
h_eT_truth_ampt.SetLineColor(4)
h_eT_truth_ampt.SetMarkerColor(4)
h_eT_truth_ampt.Draw()
emcal_detdeta_ampt.SetMarkerStyle(20)
emcal_detdeta_ampt.SetLineColor(2)
emcal_detdeta_ampt.SetMarkerColor(2)
emcal_detdeta_ampt.Draw("same")
ihcal_detdeta_ampt.SetMarkerStyle(20)
ihcal_detdeta_ampt.SetLineColor(3)
ihcal_detdeta_ampt.SetMarkerColor(3)
ihcal_detdeta_ampt.Draw("same")
ohcal_detdeta_ampt.SetMarkerStyle(20)
ohcal_detdeta_ampt.SetLineColor(6)
ohcal_detdeta_ampt.SetMarkerColor(6)
ohcal_detdeta_ampt.Draw("same")
#starline.Draw("same")
#starbox.Draw("same")
#phnxline.Draw("same")
#phnxbox.Draw("same")
#ampt_canvas.Update()
ampt_leg.Draw()
ampt_canvas.Draw()

emcal_canvas.Write()
ihcal_canvas.Write()
ohcal_canvas.Write()
emcal_corr_canvas.Write()
ihcal_corr_canvas.Write()
ohcal_corr_canvas.Write()
hijing_canvas.Write()
epos_canvas.Write()
ampt_canvas.Write()
file.Close()
