import ROOT
from ROOT import TCanvas, TFile, TProfile, TNtuple, TH1I, TH1F, TH2F, TH3F, TColor, TEfficiency
from ROOT import gROOT, gBenchmark, gRandom, gSystem
import numpy as np
import pdb
import sys

cents = ['0-5','5-10','10-20','20-30','30-40','40-50','50-60','60-70']
tag = 'MC'
outfile = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/fixed_build_prc_edit/syst_covariance/dETdeta_signed_variation_'+tag+'.root'
emcal_detdeta_dev2 = TH1F("emcal_detdeta_dev2","",8,0,8)
hcal_detdeta_dev2 = TH1F("hcal_detdeta_dev2","",8,0,8)
calo_detdeta_dev2 = TH1F("calo_detdeta_dev2","",8,0,8)
emcal_detdeta_dev3 = TH1F("emcal_detdeta_dev3","",8,0,8)
hcal_detdeta_dev3 = TH1F("hcal_detdeta_dev3","",8,0,8)
calo_detdeta_dev3 = TH1F("calo_detdeta_dev3","",8,0,8)
pos_eta_emcal_detdeta_dev2 = TH2F("pos_eta_emcal_detdeta_dev2","",3,0,3,8,0,8)
pos_eta_hcal_detdeta_dev2 = TH2F("pos_eta_hcal_detdeta_dev2","",3,0,3,8,0,8)
pos_eta_calo_detdeta_dev2 = TH2F("pos_eta_calo_detdeta_dev2","",3,0,3,8,0,8)
neg_eta_emcal_detdeta_dev2 = TH2F("neg_eta_emcal_detdeta_dev2","",3,0,3,8,0,8)
neg_eta_hcal_detdeta_dev2 = TH2F("neg_eta_hcal_detdeta_dev2","",3,0,3,8,0,8)
neg_eta_calo_detdeta_dev2 = TH2F("neg_eta_calo_detdeta_dev2","",3,0,3,8,0,8)
pos_eta_emcal_detdeta_dev3 = TH2F("pos_eta_emcal_detdeta_dev3","",3,0,3,8,0,8)
pos_eta_hcal_detdeta_dev3 = TH2F("pos_eta_hcal_detdeta_dev3","",3,0,3,8,0,8)
pos_eta_calo_detdeta_dev3 = TH2F("pos_eta_calo_detdeta_dev3","",3,0,3,8,0,8)
neg_eta_emcal_detdeta_dev3 = TH2F("neg_eta_emcal_detdeta_dev3","",3,0,3,8,0,8)
neg_eta_hcal_detdeta_dev3 = TH2F("neg_eta_hcal_detdeta_dev3","",3,0,3,8,0,8)
neg_eta_calo_detdeta_dev3 = TH2F("neg_eta_calo_detdeta_dev3","",3,0,3,8,0,8)
for c, cent in enumerate(cents):
    mcfile = '../dETdeta_analysis_allruns_run14_with_centbin_nozs_mc_reweight_'+cent+'_reweight_epos_2024.root'
    mcfile1 = '../dETdeta_analysis_allruns_run14_with_centbin_nozs_mc_reweight_'+cent+'_reweight_ampt_2024.root'
    mcfile2 = '../dETdeta_analysis_allruns_run14_with_centbin_nozs_mc_reweight_'+cent+'_reweight_hijing_2024.root'
    datafile = '../dETdeta_analysis_allruns_ana450_2024p009_100_50_50_ZS_hcal_scaled_emcal_calib_iter26_nozs_data_noweight_'+cent+'.root'
        
    f1 = ROOT.TFile.Open(mcfile)
    h_emcal_correction1 = TH1F(f1.Get("h_emcal_correction"))
    h_calo_correction1 = TH1F(f1.Get("h_calo_correction"))
    h_hcal_correction1 = TH1F(f1.Get("h_hcal_correction"))
    h_emcal_correction1.SetDirectory(0)
    h_calo_correction1.SetDirectory(0)
    h_hcal_correction1.SetDirectory(0)
    f1.Close()
    f1 = ROOT.TFile.Open(mcfile1)
    h_emcal_correction2 = TH1F(f1.Get("h_emcal_correction"))
    h_calo_correction2 = TH1F(f1.Get("h_calo_correction"))
    h_hcal_correction2 = TH1F(f1.Get("h_hcal_correction"))
    h_emcal_correction2.SetDirectory(0)
    h_calo_correction2.SetDirectory(0)
    h_hcal_correction2.SetDirectory(0)
    f1.Close()
    f1 = ROOT.TFile.Open(mcfile2)
    h_emcal_correction3 = TH1F(f1.Get("h_emcal_correction"))
    h_calo_correction3 = TH1F(f1.Get("h_calo_correction"))
    h_hcal_correction3 = TH1F(f1.Get("h_hcal_correction"))
    h_emcal_correction3.SetDirectory(0)
    h_calo_correction3.SetDirectory(0)
    h_hcal_correction3.SetDirectory(0)
    f1.Close()
    
    f2 = ROOT.TFile.Open(datafile)
    h_eT_data_emcal = TH1F(f2.Get("h_eT_eta_emcal_profile_hist"))
    h_eT_data_calo = TH1F(f2.Get("h_eT_eta_calo_profile_hist"))
    h_eT_data_hcal = TH1F(f2.Get("h_eT_eta_hcal_profile_hist"))
    h_eT_data_emcal.SetDirectory(0)
    h_eT_data_calo.SetDirectory(0)
    h_eT_data_hcal.SetDirectory(0)
    f2.Close()

    emcal_detdeta_mc1 = TH1F(h_eT_data_emcal.Clone("emcal_detdeta_mc1"))
    emcal_detdeta_mc1.Divide(h_emcal_correction1)
    calo_detdeta_mc1 = TH1F(h_eT_data_calo.Clone("calo_detdeta_mc1"))
    calo_detdeta_mc1.Divide(h_calo_correction1)
    hcal_detdeta_mc1 = TH1F(h_eT_data_hcal.Clone("hcal_detdeta_mc1"))
    hcal_detdeta_mc1.Divide(h_hcal_correction1) 

    emcal_detdeta_mc2 = TH1F(h_eT_data_emcal.Clone("emcal_detdeta_mc2"))
    emcal_detdeta_mc2.Divide(h_emcal_correction2)
    calo_detdeta_mc2 = TH1F(h_eT_data_calo.Clone("calo_detdeta_mc2"))
    calo_detdeta_mc2.Divide(h_calo_correction2)
    hcal_detdeta_mc2 = TH1F(h_eT_data_hcal.Clone("hcal_detdeta_mc2"))
    hcal_detdeta_mc2.Divide(h_hcal_correction2) 

    emcal_detdeta_mc3 = TH1F(h_eT_data_emcal.Clone("emcal_detdeta_mc3"))
    emcal_detdeta_mc3.Divide(h_emcal_correction3)
    calo_detdeta_mc3 = TH1F(h_eT_data_calo.Clone("calo_detdeta_mc3"))
    calo_detdeta_mc3.Divide(h_calo_correction3)
    hcal_detdeta_mc3 = TH1F(h_eT_data_hcal.Clone("hcal_detdeta_mc3"))
    hcal_detdeta_mc3.Divide(h_hcal_correction3)

    emcal_detdeta_dev12 = TH1F(emcal_detdeta_mc1.Clone("emcal_detdeta_dev12"))
    emcal_detdeta_dev12.SetXTitle("#eta")
    emcal_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, emcal_detdeta_dev12.GetNbinsX() + 1):
        emcal_detdeta_dev12.SetBinContent(i, emcal_detdeta_mc1.GetBinContent(i) - emcal_detdeta_mc2.GetBinContent(i))
        emcal_detdeta_dev12.SetBinError(i, np.sqrt(emcal_detdeta_mc1.GetBinError(i)**2 + emcal_detdeta_mc2.GetBinError(i)**2))

    calo_detdeta_dev12 = TH1F(calo_detdeta_mc1.Clone("calo_detdeta_dev12"))
    calo_detdeta_dev12.SetXTitle("#eta")
    calo_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, calo_detdeta_dev12.GetNbinsX() + 1):
        calo_detdeta_dev12.SetBinContent(i, calo_detdeta_mc1.GetBinContent(i) - calo_detdeta_mc2.GetBinContent(i))
        calo_detdeta_dev12.SetBinError(i, np.sqrt(calo_detdeta_mc1.GetBinError(i)**2 + calo_detdeta_mc2.GetBinError(i)**2))

    hcal_detdeta_dev12 = TH1F(hcal_detdeta_mc1.Clone("hcal_detdeta_dev12"))
    hcal_detdeta_dev12.SetXTitle("#eta")
    hcal_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, hcal_detdeta_dev12.GetNbinsX() + 1):
        hcal_detdeta_dev12.SetBinContent(i, hcal_detdeta_mc1.GetBinContent(i) - hcal_detdeta_mc2.GetBinContent(i))
        hcal_detdeta_dev12.SetBinError(i, np.sqrt(hcal_detdeta_mc1.GetBinError(i)**2 + hcal_detdeta_mc2.GetBinError(i)**2))

    emcal_detdeta_dev13 = TH1F(emcal_detdeta_mc1.Clone("emcal_detdeta_dev13"))
    emcal_detdeta_dev13.SetXTitle("#eta")
    emcal_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, emcal_detdeta_dev13.GetNbinsX() + 1):
        emcal_detdeta_dev13.SetBinContent(i, emcal_detdeta_mc1.GetBinContent(i) - emcal_detdeta_mc3.GetBinContent(i))
        emcal_detdeta_dev13.SetBinError(i, np.sqrt(emcal_detdeta_mc1.GetBinError(i)**2 + emcal_detdeta_mc3.GetBinError(i)**2))

    calo_detdeta_dev13 = TH1F(calo_detdeta_mc1.Clone("calo_detdeta_dev13"))
    calo_detdeta_dev13.SetXTitle("#eta")
    calo_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, calo_detdeta_dev13.GetNbinsX() + 1):
        calo_detdeta_dev13.SetBinContent(i, calo_detdeta_mc1.GetBinContent(i) - calo_detdeta_mc3.GetBinContent(i))
        calo_detdeta_dev13.SetBinError(i, np.sqrt(calo_detdeta_mc1.GetBinError(i)**2 + calo_detdeta_mc3.GetBinError(i)**2))

    hcal_detdeta_dev13 = TH1F(hcal_detdeta_mc1.Clone("hcal_detdeta_dev13"))
    hcal_detdeta_dev13.SetXTitle("#eta")
    hcal_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, hcal_detdeta_dev13.GetNbinsX() + 1):
        hcal_detdeta_dev13.SetBinContent(i, hcal_detdeta_mc1.GetBinContent(i) - hcal_detdeta_mc3.GetBinContent(i))
        hcal_detdeta_dev13.SetBinError(i, np.sqrt(hcal_detdeta_mc1.GetBinError(i)**2 + hcal_detdeta_mc3.GetBinError(i)**2))

    bins = emcal_detdeta_dev12.GetNbinsX()
    neg_eta_emcal_detdeta_dev2.SetBinContent(neg_eta_emcal_detdeta_dev2.GetBin(1, c+1), neg_eta_emcal_detdeta_dev2.GetBinContent(c+1) + emcal_detdeta_dev12.GetBinContent(1))
    pos_eta_emcal_detdeta_dev2.SetBinContent(pos_eta_emcal_detdeta_dev2.GetBin(1, c+1), pos_eta_emcal_detdeta_dev2.GetBinContent(c+1) + emcal_detdeta_dev12.GetBinContent(6))
    neg_eta_emcal_detdeta_dev2.SetBinContent(neg_eta_emcal_detdeta_dev2.GetBin(2, c+1), neg_eta_emcal_detdeta_dev2.GetBinContent(c+1) + emcal_detdeta_dev12.GetBinContent(2))
    pos_eta_emcal_detdeta_dev2.SetBinContent(pos_eta_emcal_detdeta_dev2.GetBin(2, c+1), pos_eta_emcal_detdeta_dev2.GetBinContent(c+1) + emcal_detdeta_dev12.GetBinContent(5))
    neg_eta_emcal_detdeta_dev2.SetBinContent(neg_eta_emcal_detdeta_dev2.GetBin(3, c+1), neg_eta_emcal_detdeta_dev2.GetBinContent(c+1) + emcal_detdeta_dev12.GetBinContent(3))
    pos_eta_emcal_detdeta_dev2.SetBinContent(pos_eta_emcal_detdeta_dev2.GetBin(3, c+1), pos_eta_emcal_detdeta_dev2.GetBinContent(c+1) + emcal_detdeta_dev12.GetBinContent(4))
    emcal_detdeta_dev12.Rebin(bins)
    emcal_detdeta_dev12.Scale(1.0/bins)
    emcal_detdeta_dev2.SetBinContent(c+1, emcal_detdeta_dev2.GetBinContent(c+1) + emcal_detdeta_dev12.GetBinContent(1))

    bins = calo_detdeta_dev12.GetNbinsX()
    neg_eta_calo_detdeta_dev2.SetBinContent(neg_eta_calo_detdeta_dev2.GetBin(1, c+1), neg_eta_calo_detdeta_dev2.GetBinContent(c+1) + calo_detdeta_dev12.GetBinContent(1))
    pos_eta_calo_detdeta_dev2.SetBinContent(pos_eta_calo_detdeta_dev2.GetBin(1, c+1), pos_eta_calo_detdeta_dev2.GetBinContent(c+1) + calo_detdeta_dev12.GetBinContent(6))
    neg_eta_calo_detdeta_dev2.SetBinContent(neg_eta_calo_detdeta_dev2.GetBin(2, c+1), neg_eta_calo_detdeta_dev2.GetBinContent(c+1) + calo_detdeta_dev12.GetBinContent(2))
    pos_eta_calo_detdeta_dev2.SetBinContent(pos_eta_calo_detdeta_dev2.GetBin(2, c+1), pos_eta_calo_detdeta_dev2.GetBinContent(c+1) + calo_detdeta_dev12.GetBinContent(5))
    neg_eta_calo_detdeta_dev2.SetBinContent(neg_eta_calo_detdeta_dev2.GetBin(3, c+1), neg_eta_calo_detdeta_dev2.GetBinContent(c+1) + calo_detdeta_dev12.GetBinContent(3))
    pos_eta_calo_detdeta_dev2.SetBinContent(pos_eta_calo_detdeta_dev2.GetBin(3, c+1), pos_eta_calo_detdeta_dev2.GetBinContent(c+1) + calo_detdeta_dev12.GetBinContent(4))
    calo_detdeta_dev12.Rebin(bins)
    calo_detdeta_dev12.Scale(1.0/bins)
    calo_detdeta_dev2.SetBinContent(c+1, calo_detdeta_dev2.GetBinContent(c+1) + calo_detdeta_dev12.GetBinContent(1))

    bins = hcal_detdeta_dev12.GetNbinsX()
    neg_eta_hcal_detdeta_dev2.SetBinContent(neg_eta_hcal_detdeta_dev2.GetBin(1, c+1), neg_eta_hcal_detdeta_dev2.GetBinContent(c+1) + hcal_detdeta_dev12.GetBinContent(1))
    pos_eta_hcal_detdeta_dev2.SetBinContent(pos_eta_hcal_detdeta_dev2.GetBin(1, c+1), pos_eta_hcal_detdeta_dev2.GetBinContent(c+1) + hcal_detdeta_dev12.GetBinContent(6))
    neg_eta_hcal_detdeta_dev2.SetBinContent(neg_eta_hcal_detdeta_dev2.GetBin(2, c+1), neg_eta_hcal_detdeta_dev2.GetBinContent(c+1) + hcal_detdeta_dev12.GetBinContent(2))
    pos_eta_hcal_detdeta_dev2.SetBinContent(pos_eta_hcal_detdeta_dev2.GetBin(2, c+1), pos_eta_hcal_detdeta_dev2.GetBinContent(c+1) + hcal_detdeta_dev12.GetBinContent(5))
    neg_eta_hcal_detdeta_dev2.SetBinContent(neg_eta_hcal_detdeta_dev2.GetBin(3, c+1), neg_eta_hcal_detdeta_dev2.GetBinContent(c+1) + hcal_detdeta_dev12.GetBinContent(3))
    pos_eta_hcal_detdeta_dev2.SetBinContent(pos_eta_hcal_detdeta_dev2.GetBin(3, c+1), pos_eta_hcal_detdeta_dev2.GetBinContent(c+1) + hcal_detdeta_dev12.GetBinContent(4))
    hcal_detdeta_dev12.Rebin(bins)
    hcal_detdeta_dev12.Scale(1.0/bins)
    hcal_detdeta_dev2.SetBinContent(c+1, hcal_detdeta_dev2.GetBinContent(c+1) + hcal_detdeta_dev12.GetBinContent(1))

    bins = emcal_detdeta_dev13.GetNbinsX()
    neg_eta_emcal_detdeta_dev3.SetBinContent(neg_eta_emcal_detdeta_dev3.GetBin(1, c+1), emcal_detdeta_dev13.GetBinContent(1))
    pos_eta_emcal_detdeta_dev3.SetBinContent(pos_eta_emcal_detdeta_dev3.GetBin(1, c+1), emcal_detdeta_dev13.GetBinContent(6))
    neg_eta_emcal_detdeta_dev3.SetBinContent(neg_eta_emcal_detdeta_dev3.GetBin(2, c+1), emcal_detdeta_dev13.GetBinContent(2))
    pos_eta_emcal_detdeta_dev3.SetBinContent(pos_eta_emcal_detdeta_dev3.GetBin(2, c+1), emcal_detdeta_dev13.GetBinContent(5))
    neg_eta_emcal_detdeta_dev3.SetBinContent(neg_eta_emcal_detdeta_dev3.GetBin(3, c+1), emcal_detdeta_dev13.GetBinContent(3))
    pos_eta_emcal_detdeta_dev3.SetBinContent(pos_eta_emcal_detdeta_dev3.GetBin(3, c+1), emcal_detdeta_dev13.GetBinContent(4))
    emcal_detdeta_dev13.Rebin(bins)
    emcal_detdeta_dev13.Scale(1.0/bins)
    emcal_detdeta_dev3.SetBinContent(c+1, emcal_detdeta_dev3.GetBinContent(c+1) + emcal_detdeta_dev13.GetBinContent(1))

    bins = calo_detdeta_dev13.GetNbinsX()
    neg_eta_calo_detdeta_dev3.SetBinContent(neg_eta_calo_detdeta_dev3.GetBin(1, c+1), calo_detdeta_dev13.GetBinContent(1))
    pos_eta_calo_detdeta_dev3.SetBinContent(pos_eta_calo_detdeta_dev3.GetBin(1, c+1), calo_detdeta_dev13.GetBinContent(6))
    neg_eta_calo_detdeta_dev3.SetBinContent(neg_eta_calo_detdeta_dev3.GetBin(2, c+1), calo_detdeta_dev13.GetBinContent(2))
    pos_eta_calo_detdeta_dev3.SetBinContent(pos_eta_calo_detdeta_dev3.GetBin(2, c+1), calo_detdeta_dev13.GetBinContent(5))
    neg_eta_calo_detdeta_dev3.SetBinContent(neg_eta_calo_detdeta_dev3.GetBin(3, c+1), calo_detdeta_dev13.GetBinContent(3))
    pos_eta_calo_detdeta_dev3.SetBinContent(pos_eta_calo_detdeta_dev3.GetBin(3, c+1), calo_detdeta_dev13.GetBinContent(4))
    calo_detdeta_dev13.Rebin(bins)
    calo_detdeta_dev13.Scale(1.0/bins)
    calo_detdeta_dev3.SetBinContent(c+1, calo_detdeta_dev3.GetBinContent(c+1) + calo_detdeta_dev13.GetBinContent(1))

    bins = hcal_detdeta_dev13.GetNbinsX()
    neg_eta_hcal_detdeta_dev3.SetBinContent(neg_eta_hcal_detdeta_dev3.GetBin(1, c+1), hcal_detdeta_dev13.GetBinContent(1))
    pos_eta_hcal_detdeta_dev3.SetBinContent(pos_eta_hcal_detdeta_dev3.GetBin(1, c+1), hcal_detdeta_dev13.GetBinContent(6))
    neg_eta_hcal_detdeta_dev3.SetBinContent(neg_eta_hcal_detdeta_dev3.GetBin(2, c+1), hcal_detdeta_dev13.GetBinContent(2))
    pos_eta_hcal_detdeta_dev3.SetBinContent(pos_eta_hcal_detdeta_dev3.GetBin(2, c+1), hcal_detdeta_dev13.GetBinContent(5))
    neg_eta_hcal_detdeta_dev3.SetBinContent(neg_eta_hcal_detdeta_dev3.GetBin(3, c+1), hcal_detdeta_dev13.GetBinContent(3))
    pos_eta_hcal_detdeta_dev3.SetBinContent(pos_eta_hcal_detdeta_dev3.GetBin(3, c+1), hcal_detdeta_dev13.GetBinContent(4))
    hcal_detdeta_dev13.Rebin(bins)
    hcal_detdeta_dev13.Scale(1.0/bins)
    hcal_detdeta_dev3.SetBinContent(c+1, hcal_detdeta_dev3.GetBinContent(c+1) + hcal_detdeta_dev13.GetBinContent(1))


    
file = ROOT.TFile(outfile, "RECREATE")
file.cd()
pos_eta_emcal_detdeta_dev2.Write()
pos_eta_calo_detdeta_dev2.Write()
pos_eta_hcal_detdeta_dev2.Write()
neg_eta_emcal_detdeta_dev2.Write()
neg_eta_calo_detdeta_dev2.Write()
neg_eta_hcal_detdeta_dev2.Write()
pos_eta_emcal_detdeta_dev3.Write()
pos_eta_calo_detdeta_dev3.Write()
pos_eta_hcal_detdeta_dev3.Write()
neg_eta_emcal_detdeta_dev3.Write()
neg_eta_calo_detdeta_dev3.Write()
neg_eta_hcal_detdeta_dev3.Write()
emcal_detdeta_dev2.Write()
calo_detdeta_dev2.Write()
hcal_detdeta_dev2.Write()
emcal_detdeta_dev3.Write()
calo_detdeta_dev3.Write()
hcal_detdeta_dev3.Write()
file.Write()
file.Close()