import ROOT
from ROOT import TCanvas, TFile, TProfile, TNtuple, TH1I, TH1F, TH2F, TH3F, TColor, TEfficiency
from ROOT import gROOT, gBenchmark, gRandom, gSystem
import numpy as np
import pdb
import sys

gROOT.LoadMacro("/sphenix/u/egm2153/spring_2023/sPhenixStyle.C");
gROOT.ProcessLine("SetsPhenixStyle()")

rgb = [[230, 25, 75], [60, 180, 75], [255, 225, 25], [0, 130, 200], [245, 130, 48], [145, 30, 180], [70, 240, 240], [240, 50, 230], [210, 245, 60], [250, 190, 212], [0, 128, 128], [220, 190, 255], [170, 110, 40], [255, 250, 200], [128, 0, 0], [170, 255, 195], [128, 128, 0], [255, 215, 180], [0, 0, 128], [128, 128, 128], [34, 139, 34], [0, 0, 0]]
colors = [TColor.GetColor(rgb[i][0],rgb[i][1],rgb[i][2]) for i in range(len(rgb))]

cents = ['0-5','5-10','10-20','20-30','30-40','40-50','50-60']
tag = 'run_by_run'
for cent in cents:
    mcfile = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/fixed_build/dETdeta_analysis_allruns_run14_with_npart_nozs_mc_reweight_'+cent+'_reweight_epos_2024.root'
    mcfile1 = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/run_by_run_syst/dETdeta_analysis_allruns_run54911_acceptance_nozs_mc_reweight_'+cent+'_reweight_epos_2024.root'
    mcfile2 = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/run_by_run_syst/dETdeta_analysis_allruns_run54914_acceptance_nozs_mc_reweight_'+cent+'_reweight_epos_2024.root'
    datafile = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/fixed_build/dETdeta_analysis_allruns_ana450_2024p009_100_50_50_ZS_hcal_tsc_emcal_calib_iter15_nozs_data_noweight_'+cent+'.root'
    datafile1 = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/run_by_run_syst/dETdeta_analysis_allruns_ana450_2024p009_54911_nozs_data_noweight_'+cent+'.root'
    datafile2 = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/run_by_run_syst/dETdeta_analysis_allruns_ana450_2024p009_54914_nozs_data_noweight_'+cent+'.root'
    outfile = '/sphenix/user/egm2153/calib_study/detdeta/analysis/Run2024/fixed_build/dETdeta_variation_'+tag+'_'+cent+'.root'

    f1 = ROOT.TFile.Open(mcfile)
    h_emcal_correction1 = TH1F(f1.Get("h_emcal_correction"))
    h_ihcal_correction1 = TH1F(f1.Get("h_ihcal_correction"))
    h_ohcal_correction1 = TH1F(f1.Get("h_ohcal_correction"))
    h_calo_correction1 = TH1F(f1.Get("h_calo_correction"))
    h_hcal_correction1 = TH1F(f1.Get("h_hcal_correction"))
    h_emcal_correction1.SetDirectory(0)
    h_ihcal_correction1.SetDirectory(0)
    h_ohcal_correction1.SetDirectory(0)
    h_calo_correction1.SetDirectory(0)
    h_hcal_correction1.SetDirectory(0)
    f1.Close()

    f1 = ROOT.TFile.Open(mcfile1)
    h_emcal_correction2 = TH1F(f1.Get("h_emcal_correction"))
    h_ihcal_correction2 = TH1F(f1.Get("h_ihcal_correction"))
    h_ohcal_correction2 = TH1F(f1.Get("h_ohcal_correction"))
    h_calo_correction2 = TH1F(f1.Get("h_calo_correction"))
    h_hcal_correction2 = TH1F(f1.Get("h_hcal_correction"))
    h_emcal_correction2.SetDirectory(0)
    h_ihcal_correction2.SetDirectory(0)
    h_ohcal_correction2.SetDirectory(0)
    h_calo_correction2.SetDirectory(0)
    h_hcal_correction2.SetDirectory(0)
    f1.Close()

    f1 = ROOT.TFile.Open(mcfile2)
    h_emcal_correction3 = TH1F(f1.Get("h_emcal_correction"))
    h_ihcal_correction3 = TH1F(f1.Get("h_ihcal_correction"))
    h_ohcal_correction3 = TH1F(f1.Get("h_ohcal_correction"))
    h_calo_correction3 = TH1F(f1.Get("h_calo_correction"))
    h_hcal_correction3 = TH1F(f1.Get("h_hcal_correction"))
    h_emcal_correction3.SetDirectory(0)
    h_ihcal_correction3.SetDirectory(0)
    h_ohcal_correction3.SetDirectory(0)
    h_calo_correction3.SetDirectory(0)
    h_hcal_correction3.SetDirectory(0)
    f1.Close()
    
    f2 = ROOT.TFile.Open(datafile)
    h_eT_data_emcal1 = TH1F(f2.Get("h_eT_eta_emcal_profile_hist"))
    h_eT_data_ihcal1 = TH1F(f2.Get("h_eT_eta_ihcal_profile_hist"))
    h_eT_data_ohcal1 = TH1F(f2.Get("h_eT_eta_ohcal_profile_hist"))
    h_eT_data_calo1 = TH1F(f2.Get("h_eT_eta_calo_profile_hist"))
    h_eT_data_hcal1 = TH1F(f2.Get("h_eT_eta_hcal_profile_hist"))
    h_eT_data_emcal1.SetDirectory(0)
    h_eT_data_ihcal1.SetDirectory(0)
    h_eT_data_ohcal1.SetDirectory(0)
    h_eT_data_calo1.SetDirectory(0)
    h_eT_data_hcal1.SetDirectory(0)
    f2.Close()

    f3 = ROOT.TFile.Open(datafile1)
    h_eT_data_emcal2 = TH1F(f3.Get("h_eT_eta_emcal_profile_hist"))
    h_eT_data_ihcal2 = TH1F(f3.Get("h_eT_eta_ihcal_profile_hist"))
    h_eT_data_ohcal2 = TH1F(f3.Get("h_eT_eta_ohcal_profile_hist"))
    h_eT_data_calo2 = TH1F(f3.Get("h_eT_eta_calo_profile_hist"))
    h_eT_data_hcal2 = TH1F(f3.Get("h_eT_eta_hcal_profile_hist"))
    h_eT_data_emcal2.SetDirectory(0)
    h_eT_data_ihcal2.SetDirectory(0)
    h_eT_data_ohcal2.SetDirectory(0)
    h_eT_data_calo2.SetDirectory(0)
    h_eT_data_hcal2.SetDirectory(0)
    f3.Close()

    f4 = ROOT.TFile.Open(datafile2)
    h_eT_data_emcal3 = TH1F(f4.Get("h_eT_eta_emcal_profile_hist"))
    h_eT_data_ihcal3 = TH1F(f4.Get("h_eT_eta_ihcal_profile_hist"))
    h_eT_data_ohcal3 = TH1F(f4.Get("h_eT_eta_ohcal_profile_hist"))
    h_eT_data_calo3 = TH1F(f4.Get("h_eT_eta_calo_profile_hist"))
    h_eT_data_hcal3 = TH1F(f4.Get("h_eT_eta_hcal_profile_hist"))
    h_eT_data_emcal3.SetDirectory(0)
    h_eT_data_ihcal3.SetDirectory(0)
    h_eT_data_ohcal3.SetDirectory(0)
    h_eT_data_calo3.SetDirectory(0)
    h_eT_data_hcal3.SetDirectory(0)
    f4.Close()
    
    file = ROOT.TFile(outfile, "RECREATE")

    emcal_detdeta_data1 = TH1F(h_eT_data_emcal1.Clone("emcal_detdeta_data1"))
    emcal_detdeta_data1.Divide(h_emcal_correction1)
    ihcal_detdeta_data1 = TH1F(h_eT_data_ihcal1.Clone("ihcal_detdeta_data1"))
    ihcal_detdeta_data1.Divide(h_ihcal_correction1)
    ohcal_detdeta_data1 = TH1F(h_eT_data_ohcal1.Clone("ohcal_detdeta_data1"))
    ohcal_detdeta_data1.Divide(h_ohcal_correction1)
    calo_detdeta_data1 = TH1F(h_eT_data_calo1.Clone("calo_detdeta_data1"))
    calo_detdeta_data1.Divide(h_calo_correction1)
    hcal_detdeta_data1 = TH1F(h_eT_data_hcal1.Clone("hcal_detdeta_data1"))
    hcal_detdeta_data1.Divide(h_hcal_correction1) 

    emcal_detdeta_data2 = TH1F(h_eT_data_emcal2.Clone("emcal_detdeta_data2"))
    emcal_detdeta_data2.Divide(h_emcal_correction2)
    ihcal_detdeta_data2 = TH1F(h_eT_data_ihcal2.Clone("ihcal_detdeta_data2"))
    ihcal_detdeta_data2.Divide(h_ihcal_correction2)
    ohcal_detdeta_data2 = TH1F(h_eT_data_ohcal2.Clone("ohcal_detdeta_data2"))
    ohcal_detdeta_data2.Divide(h_ohcal_correction2)
    calo_detdeta_data2 = TH1F(h_eT_data_calo2.Clone("calo_detdeta_data2"))
    calo_detdeta_data2.Divide(h_calo_correction2)
    hcal_detdeta_data2 = TH1F(h_eT_data_hcal2.Clone("hcal_detdeta_data2"))
    hcal_detdeta_data2.Divide(h_hcal_correction2) 

    emcal_detdeta_data3 = TH1F(h_eT_data_emcal3.Clone("emcal_detdeta_data3"))
    emcal_detdeta_data3.Divide(h_emcal_correction3)
    ihcal_detdeta_data3 = TH1F(h_eT_data_ihcal3.Clone("ihcal_detdeta_data3"))
    ihcal_detdeta_data3.Divide(h_ihcal_correction3)
    ohcal_detdeta_data3 = TH1F(h_eT_data_ohcal3.Clone("ohcal_detdeta_data3"))
    ohcal_detdeta_data3.Divide(h_ohcal_correction3)
    calo_detdeta_data3 = TH1F(h_eT_data_calo3.Clone("calo_detdeta_data3"))
    calo_detdeta_data3.Divide(h_calo_correction3)
    hcal_detdeta_data3 = TH1F(h_eT_data_hcal3.Clone("hcal_detdeta_data3"))
    hcal_detdeta_data3.Divide(h_hcal_correction3)

    emcal_detdeta_dev12 = TH1F(emcal_detdeta_data1.Clone("emcal_detdeta_dev12"))
    emcal_detdeta_dev12.SetXTitle("#eta")
    emcal_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, emcal_detdeta_dev12.GetNbinsX() + 1):
        emcal_detdeta_dev12.SetBinContent(i, np.abs(emcal_detdeta_data1.GetBinContent(i) - emcal_detdeta_data2.GetBinContent(i)))
        emcal_detdeta_dev12.SetBinError(i, np.sqrt(emcal_detdeta_data1.GetBinError(i)**2 + emcal_detdeta_data2.GetBinError(i)**2))

    ihcal_detdeta_dev12 = TH1F(ihcal_detdeta_data1.Clone("ihcal_detdeta_dev12"))
    ihcal_detdeta_dev12.SetXTitle("#eta")
    ihcal_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, ihcal_detdeta_dev12.GetNbinsX() + 1):
        ihcal_detdeta_dev12.SetBinContent(i, np.abs(ihcal_detdeta_data1.GetBinContent(i) - ihcal_detdeta_data2.GetBinContent(i)))
        ihcal_detdeta_dev12.SetBinError(i, np.sqrt(ihcal_detdeta_data1.GetBinError(i)**2 + ihcal_detdeta_data2.GetBinError(i)**2))

    ohcal_detdeta_dev12 = TH1F(ohcal_detdeta_data1.Clone("ohcal_detdeta_dev12"))
    ohcal_detdeta_dev12.SetXTitle("#eta")
    ohcal_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, ohcal_detdeta_dev12.GetNbinsX() + 1):
        ohcal_detdeta_dev12.SetBinContent(i, np.abs(ohcal_detdeta_data1.GetBinContent(i) - ohcal_detdeta_data2.GetBinContent(i)))
        ohcal_detdeta_dev12.SetBinError(i, np.sqrt(ohcal_detdeta_data1.GetBinError(i)**2 + ohcal_detdeta_data2.GetBinError(i)**2))

    calo_detdeta_dev12 = TH1F(calo_detdeta_data1.Clone("calo_detdeta_dev12"))
    calo_detdeta_dev12.SetXTitle("#eta")
    calo_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, calo_detdeta_dev12.GetNbinsX() + 1):
        calo_detdeta_dev12.SetBinContent(i, np.abs(calo_detdeta_data1.GetBinContent(i) - calo_detdeta_data2.GetBinContent(i)))
        calo_detdeta_dev12.SetBinError(i, np.sqrt(calo_detdeta_data1.GetBinError(i)**2 + calo_detdeta_data2.GetBinError(i)**2))

    hcal_detdeta_dev12 = TH1F(hcal_detdeta_data1.Clone("hcal_detdeta_dev12"))
    hcal_detdeta_dev12.SetXTitle("#eta")
    hcal_detdeta_dev12.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, hcal_detdeta_dev12.GetNbinsX() + 1):
        hcal_detdeta_dev12.SetBinContent(i, np.abs(hcal_detdeta_data1.GetBinContent(i) - hcal_detdeta_data2.GetBinContent(i)))
        hcal_detdeta_dev12.SetBinError(i, np.sqrt(hcal_detdeta_data1.GetBinError(i)**2 + hcal_detdeta_data2.GetBinError(i)**2))

    emcal_detdeta_dev13 = TH1F(emcal_detdeta_data1.Clone("emcal_detdeta_dev13"))
    emcal_detdeta_dev13.SetXTitle("#eta")
    emcal_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, emcal_detdeta_dev13.GetNbinsX() + 1):
        emcal_detdeta_dev13.SetBinContent(i, np.abs(emcal_detdeta_data1.GetBinContent(i) - emcal_detdeta_data3.GetBinContent(i)))
        emcal_detdeta_dev13.SetBinError(i, np.sqrt(emcal_detdeta_data1.GetBinError(i)**2 + emcal_detdeta_data3.GetBinError(i)**2))

    ihcal_detdeta_dev13 = TH1F(ihcal_detdeta_data1.Clone("ihcal_detdeta_dev13"))
    ihcal_detdeta_dev13.SetXTitle("#eta")
    ihcal_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, ihcal_detdeta_dev13.GetNbinsX() + 1):
        ihcal_detdeta_dev13.SetBinContent(i, np.abs(ihcal_detdeta_data1.GetBinContent(i) - ihcal_detdeta_data3.GetBinContent(i)))
        ihcal_detdeta_dev13.SetBinError(i, np.sqrt(ihcal_detdeta_data1.GetBinError(i)**2 + ihcal_detdeta_data3.GetBinError(i)**2))

    ohcal_detdeta_dev13 = TH1F(ohcal_detdeta_data1.Clone("ohcal_detdeta_dev13"))
    ohcal_detdeta_dev13.SetXTitle("#eta")
    ohcal_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, ohcal_detdeta_dev13.GetNbinsX() + 1):
        ohcal_detdeta_dev13.SetBinContent(i, np.abs(ohcal_detdeta_data1.GetBinContent(i) - ohcal_detdeta_data3.GetBinContent(i)))
        ohcal_detdeta_dev13.SetBinError(i, np.sqrt(ohcal_detdeta_data1.GetBinError(i)**2 + ohcal_detdeta_data3.GetBinError(i)**2))

    calo_detdeta_dev13 = TH1F(calo_detdeta_data1.Clone("calo_detdeta_dev13"))
    calo_detdeta_dev13.SetXTitle("#eta")
    calo_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, calo_detdeta_dev13.GetNbinsX() + 1):
        calo_detdeta_dev13.SetBinContent(i, np.abs(calo_detdeta_data1.GetBinContent(i) - calo_detdeta_data3.GetBinContent(i)))
        calo_detdeta_dev13.SetBinError(i, np.sqrt(calo_detdeta_data1.GetBinError(i)**2 + calo_detdeta_data3.GetBinError(i)**2))

    hcal_detdeta_dev13 = TH1F(hcal_detdeta_data1.Clone("hcal_detdeta_dev13"))
    hcal_detdeta_dev13.SetXTitle("#eta")
    hcal_detdeta_dev13.SetYTitle("dE_{T}/d#eta dev. [GeV]")
    for i in range(1, hcal_detdeta_dev13.GetNbinsX() + 1):
        hcal_detdeta_dev13.SetBinContent(i, np.abs(hcal_detdeta_data1.GetBinContent(i) - hcal_detdeta_data3.GetBinContent(i)))
        hcal_detdeta_dev13.SetBinError(i, np.sqrt(hcal_detdeta_data1.GetBinError(i)**2 + hcal_detdeta_data3.GetBinError(i)**2))

    emcal_detdeta_dev = emcal_detdeta_dev12.Clone("emcal_detdeta_dev")
    for i in range(1, emcal_detdeta_dev12.GetNbinsX() + 1):
        emcal_detdeta_dev.SetBinContent(i, np.average([emcal_detdeta_dev12.GetBinContent(i), emcal_detdeta_dev13.GetBinContent(i)]))
        emcal_detdeta_dev.SetBinError(i, 0)
    
    ihcal_detdeta_dev = ihcal_detdeta_dev12.Clone("ihcal_detdeta_dev")
    for i in range(1, ihcal_detdeta_dev12.GetNbinsX() + 1):
        ihcal_detdeta_dev.SetBinContent(i, np.average([ihcal_detdeta_dev12.GetBinContent(i), ihcal_detdeta_dev13.GetBinContent(i)]))
        ihcal_detdeta_dev.SetBinError(i, 0)
    
    ohcal_detdeta_dev = ohcal_detdeta_dev12.Clone("ohcal_detdeta_dev")
    for i in range(1, ohcal_detdeta_dev12.GetNbinsX() + 1):
        ohcal_detdeta_dev.SetBinContent(i, np.average([ohcal_detdeta_dev12.GetBinContent(i), ohcal_detdeta_dev13.GetBinContent(i)]))
        ohcal_detdeta_dev.SetBinError(i, 0)
    
    calo_detdeta_dev = calo_detdeta_dev12.Clone("calo_detdeta_dev")
    for i in range(1, calo_detdeta_dev12.GetNbinsX() + 1):
        calo_detdeta_dev.SetBinContent(i, np.average([calo_detdeta_dev12.GetBinContent(i), calo_detdeta_dev13.GetBinContent(i)]))
        calo_detdeta_dev.SetBinError(i, 0)
        
    hcal_detdeta_dev = hcal_detdeta_dev12.Clone("hcal_detdeta_dev")
    for i in range(1, hcal_detdeta_dev12.GetNbinsX() + 1):
        hcal_detdeta_dev.SetBinContent(i, np.average([hcal_detdeta_dev12.GetBinContent(i), hcal_detdeta_dev13.GetBinContent(i)]))
        hcal_detdeta_dev.SetBinError(i, 0)
    
    emcal_detdeta_per = emcal_detdeta_dev.Clone("emcal_detdeta_per")
    hcal_detdeta_per = hcal_detdeta_dev.Clone("hcal_detdeta_per")
    calo_detdeta_per = calo_detdeta_dev.Clone("calo_detdeta_per")
    ihcal_detdeta_per = ihcal_detdeta_dev.Clone("ihcal_detdeta_per")
    ohcal_detdeta_per = ohcal_detdeta_dev.Clone("ohcal_detdeta_per")
    emcal_detdeta_per.Divide(emcal_detdeta_data1)
    hcal_detdeta_per.Divide(hcal_detdeta_data1)
    calo_detdeta_per.Divide(calo_detdeta_data1)
    ihcal_detdeta_per.Divide(ihcal_detdeta_data1)
    ohcal_detdeta_per.Divide(ohcal_detdeta_data1)

    if cent == '0-5':
        emcal_canvas = TCanvas("emcal_canvas","",600,500)
        leg = ROOT.TLegend(.45,.55,.8,.89)
        leg.AddEntry("","#bf{#it{sPHENIX}} Internal","")
        leg.AddEntry("",f"{cent}% cent.","")
        emcal_canvas.SetLeftMargin(0.18)
        leg.SetBorderSize(0)
        leg.AddEntry(emcal_detdeta_data1,"Run 54912","lep")
        leg.AddEntry(emcal_detdeta_data2,"Run 54911","lep")
        leg.AddEntry(emcal_detdeta_data3,"Run 54914","lep")
        emcal_detdeta_data1.SetStats(0)
        emcal_detdeta_data1.SetLineColor(colors[0])
        emcal_detdeta_data1.SetMarkerColor(colors[0])
        emcal_detdeta_data2.SetStats(0)
        emcal_detdeta_data2.SetLineColor(colors[1])
        emcal_detdeta_data2.SetMarkerColor(colors[1])
        emcal_detdeta_data3.SetStats(0)
        emcal_detdeta_data3.SetLineColor(colors[3])
        emcal_detdeta_data3.SetMarkerColor(colors[3])
        emcal_detdeta_data1.GetYaxis().SetRangeUser(400,1100)
        emcal_detdeta_data1.SetXTitle("#eta")
        emcal_detdeta_data1.SetYTitle("EMCal dE_{T}/d#eta [GeV]")
        emcal_detdeta_data1.GetYaxis().SetTitleOffset(1.8)
        emcal_detdeta_data1.Draw()
        emcal_detdeta_data2.Draw('same')
        emcal_detdeta_data3.Draw('same')
        leg.Draw()
        emcal_canvas.SaveAs('syst_plots/run_by_run_emcal_'+cent+'.png')

        ihcal_canvas = TCanvas("ihcal_canvas","",600,500)
        leg = ROOT.TLegend(.45,.55,.8,.89)
        leg.AddEntry("","#bf{#it{sPHENIX}} Internal","")
        leg.AddEntry("",f"{cent}% cent.","")
        ihcal_canvas.SetLeftMargin(0.18)
        leg.SetBorderSize(0)
        leg.AddEntry(ihcal_detdeta_data1,"Run 54912","lep")
        leg.AddEntry(ihcal_detdeta_data2,"Run 54911","lep")
        leg.AddEntry(ihcal_detdeta_data3,"Run 54914","lep")
        ihcal_detdeta_data1.SetStats(0)
        ihcal_detdeta_data1.SetLineColor(colors[0])
        ihcal_detdeta_data1.SetMarkerColor(colors[0])
        ihcal_detdeta_data2.SetStats(0)
        ihcal_detdeta_data2.SetLineColor(colors[1])
        ihcal_detdeta_data2.SetMarkerColor(colors[1])
        ihcal_detdeta_data3.SetStats(0)
        ihcal_detdeta_data3.SetLineColor(colors[3])
        ihcal_detdeta_data3.SetMarkerColor(colors[3])
        ihcal_detdeta_data1.GetYaxis().SetRangeUser(400,1100)
        ihcal_detdeta_data1.SetXTitle("#eta")
        ihcal_detdeta_data1.SetYTitle("IHCal dE_{T}/d#eta [GeV]")
        ihcal_detdeta_data1.GetYaxis().SetTitleOffset(1.8)
        ihcal_detdeta_data1.Draw()
        ihcal_detdeta_data2.Draw('same')
        ihcal_detdeta_data3.Draw('same')
        leg.Draw()
        ihcal_canvas.SaveAs('syst_plots/run_by_run_ihcal_'+cent+'.png')

        ohcal_canvas = TCanvas("ohcal_canvas","",600,500)
        leg = ROOT.TLegend(.45,.55,.8,.89)
        leg.AddEntry("","#bf{#it{sPHENIX}} Internal","")
        leg.AddEntry("",f"{cent}% cent.","")
        ohcal_canvas.SetLeftMargin(0.18)
        leg.SetBorderSize(0)
        leg.AddEntry(ohcal_detdeta_data1,"Run 54912","lep")
        leg.AddEntry(ohcal_detdeta_data2,"Run 54911","lep")
        leg.AddEntry(ohcal_detdeta_data3,"Run 54914","lep")
        ohcal_detdeta_data1.SetStats(0)
        ohcal_detdeta_data1.SetLineColor(colors[0])
        ohcal_detdeta_data1.SetMarkerColor(colors[0])
        ohcal_detdeta_data2.SetStats(0)
        ohcal_detdeta_data2.SetLineColor(colors[1])
        ohcal_detdeta_data2.SetMarkerColor(colors[1])
        ohcal_detdeta_data3.SetStats(0)
        ohcal_detdeta_data3.SetLineColor(colors[3])
        ohcal_detdeta_data3.SetMarkerColor(colors[3])
        ohcal_detdeta_data1.GetYaxis().SetRangeUser(400,1100)
        ohcal_detdeta_data1.SetXTitle("#eta")
        ohcal_detdeta_data1.SetYTitle("OHCal dE_{T}/d#eta [GeV]")
        ohcal_detdeta_data1.GetYaxis().SetTitleOffset(1.8)
        ohcal_detdeta_data1.Draw()
        ohcal_detdeta_data2.Draw('same')
        ohcal_detdeta_data3.Draw('same')
        leg.Draw()
        ohcal_canvas.SaveAs('syst_plots/run_by_run_ohcal_'+cent+'.png')

        calo_canvas = TCanvas("calo_canvas","",600,500)
        leg = ROOT.TLegend(.45,.55,.8,.89)
        leg.AddEntry("","#bf{#it{sPHENIX}} Internal","")
        leg.AddEntry("",f"{cent}% cent.","")
        calo_canvas.SetLeftMargin(0.18)
        leg.SetBorderSize(0)
        leg.AddEntry(calo_detdeta_data1,"Run 54912","lep")
        leg.AddEntry(calo_detdeta_data2,"Run 54911","lep")
        leg.AddEntry(calo_detdeta_data3,"Run 54914","lep")
        calo_detdeta_data1.SetStats(0)
        calo_detdeta_data1.SetLineColor(colors[0])
        calo_detdeta_data1.SetMarkerColor(colors[0])
        calo_detdeta_data2.SetStats(0)
        calo_detdeta_data2.SetLineColor(colors[1])
        calo_detdeta_data2.SetMarkerColor(colors[1])
        calo_detdeta_data3.SetStats(0)
        calo_detdeta_data3.SetLineColor(colors[3])
        calo_detdeta_data3.SetMarkerColor(colors[3])
        calo_detdeta_data1.GetYaxis().SetRangeUser(400,1100)
        calo_detdeta_data1.SetXTitle("#eta")
        calo_detdeta_data1.SetYTitle("dE_{T}/d#eta [GeV]")
        calo_detdeta_data1.GetYaxis().SetTitleOffset(1.8)
        calo_detdeta_data1.Draw()
        calo_detdeta_data2.Draw('same')
        calo_detdeta_data3.Draw('same')
        leg.Draw()
        calo_canvas.SaveAs('syst_plots/run_by_run_calo_'+cent+'.png')

        hcal_canvas = TCanvas("hcal_canvas","",600,500)
        leg = ROOT.TLegend(.45,.55,.8,.89)
        leg.AddEntry("","#bf{#it{sPHENIX}} Internal","")
        leg.AddEntry("",f"{cent}% cent.","")
        hcal_canvas.SetLeftMargin(0.18)
        leg.SetBorderSize(0)
        leg.AddEntry(hcal_detdeta_data1,"Run 54912","lep")
        leg.AddEntry(hcal_detdeta_data2,"Run 54911","lep")
        leg.AddEntry(hcal_detdeta_data3,"Run 54914","lep")
        hcal_detdeta_data1.SetStats(0)
        hcal_detdeta_data1.SetLineColor(colors[0])
        hcal_detdeta_data1.SetMarkerColor(colors[0])
        hcal_detdeta_data2.SetStats(0)
        hcal_detdeta_data2.SetLineColor(colors[1])
        hcal_detdeta_data2.SetMarkerColor(colors[1])
        hcal_detdeta_data3.SetStats(0)
        hcal_detdeta_data3.SetLineColor(colors[3])
        hcal_detdeta_data3.SetMarkerColor(colors[3])
        hcal_detdeta_data1.GetYaxis().SetRangeUser(400,1100)
        hcal_detdeta_data1.SetXTitle("#eta")
        hcal_detdeta_data1.SetYTitle("HCal dE_{T}/d#eta [GeV]")
        hcal_detdeta_data1.GetYaxis().SetTitleOffset(1.8)
        hcal_detdeta_data1.Draw()
        hcal_detdeta_data2.Draw('same')
        hcal_detdeta_data3.Draw('same')
        leg.Draw()
        hcal_canvas.SaveAs('syst_plots/run_by_run_hcal_'+cent+'.png')

        canvas = TCanvas("canvas","",600,500)
        leg = ROOT.TLegend(.45,.55,.8,.89)
        leg.AddEntry("","#bf{#it{sPHENIX}} Internal","")
        leg.AddEntry("",f"{cent}% cent.","")
        canvas.SetLeftMargin(0.18)
        leg.SetBorderSize(0)
        leg.AddEntry(emcal_detdeta_per,"EMCal","lep")
        leg.AddEntry(hcal_detdeta_per,"HCal","lep")
        leg.AddEntry(calo_detdeta_per,"Full Calo","lep")
        leg.AddEntry(ihcal_detdeta_per,"IHCal","lep")
        leg.AddEntry(ohcal_detdeta_per,"OHCal","lep")
        emcal_detdeta_per.SetStats(0)
        emcal_detdeta_per.SetLineColor(colors[0])
        emcal_detdeta_per.SetMarkerColor(colors[0])
        ihcal_detdeta_per.SetStats(0)
        ihcal_detdeta_per.SetLineColor(colors[1])
        ihcal_detdeta_per.SetMarkerColor(colors[1])
        ohcal_detdeta_per.SetStats(0)
        ohcal_detdeta_per.SetLineColor(colors[3])
        ohcal_detdeta_per.SetMarkerColor(colors[3])
        calo_detdeta_per.SetStats(0)
        calo_detdeta_per.SetLineColor(colors[4])
        calo_detdeta_per.SetMarkerColor(colors[4])
        hcal_detdeta_per.SetStats(0)
        hcal_detdeta_per.SetLineColor(colors[5])
        hcal_detdeta_per.SetMarkerColor(colors[5])
        emcal_detdeta_per.GetYaxis().SetRangeUser(0,0.04)
        emcal_detdeta_per.SetXTitle("#eta")
        emcal_detdeta_per.SetYTitle("Run by run dE_{T}/d#eta Uncertainty")
        emcal_detdeta_per.GetYaxis().SetTitleOffset(1.8)
        emcal_detdeta_per.Draw()
        ihcal_detdeta_per.Draw('same')
        ohcal_detdeta_per.Draw('same')
        calo_detdeta_per.Draw('same')
        hcal_detdeta_per.Draw('same')
        leg.Draw()
        canvas.SaveAs('syst_plots/run_by_run_syst_'+cent+'.png')

    emcal_detdeta_dev.Write()
    ihcal_detdeta_dev.Write()
    ohcal_detdeta_dev.Write()
    calo_detdeta_dev.Write()
    hcal_detdeta_dev.Write()
    file.Close()